import type { Product, Service } from "./types";

export const services: Service[] = [
  {
    title: "Instalacija Windowsa 10 i 11",
    description:
      "Osiguravamo brzu i pouzdanu instalaciju najnovijih verzija Windows operativnog sustava.",
  },
  {
    title: "Spašavanje/Vraćanje Podataka",
    description:
      "Pomažemo Vam da vratite izgubljene podatke i zaštitite važne informacije.",
  },
  {
    title: "Čišćenje Računala",
    description: "Temeljito čišćenje i optimizacija računala za bolju izvedbu.",
  },
  {
    title: "Računalno Programiranje",
    description:
      "Razvijamo prilagođene softverske aplikacije koje zadovoljavaju specifične potrebe Vašeg poslovanja.",
  },
  {
    title: "Savjetovanje",
    description:
      "Pružamo stručne savjete za upravljanje radom programa i računala, pomažući Vam da maksimalno iskoristite svoje resurse.",
  },
  {
    title: "Održavanje Računala",
    description:
      "Redovito održavanje i tehnička podrška za osiguranje dugotrajne i pouzdane upotrebe Vaših računala.",
  },
];

export const products: Product[] = [
  {
    title: "Windows 10 Professional Digitalna Licenca",
    shortTitle: "Windows 10 Pro",
    slug: "win-10-pro",
    image: "/images/products/win-10-pro.png",
    price: "33.00",
    infos: [
      "Izdavanje običnog i R1 računa",
      "Nova, nekorištena licenca - ključ",
      "Ključ aktivira jedno računalo doživotno",
      "Professional izdanje",
      "ESD (elektronička dostava putem emaila)",
      "Popust na količinu",
      "Uvijek na stanju, isporuka u najkraćem roku",
      "Licencu (ključ) šaljemo na email",
    ],
  },
  {
    title: "Windows 10 Home Digitalna Licenca",
    shortTitle: "Windows 10 Home",
    slug: "win-10-home",
    image: "/images/products/win-10-home.png",
    price: "33.00",
    infos: [
      "Izdavanje običnog i R1 računa",
      "Nova, nekorištena licenca - ključ",
      "Ključ aktivira jedno računalo doživotno",
      "Professional izdanje",
      "ESD (elektronička dostava putem emaila)",
      "Popust na količinu",
      "Uvijek na stanju, isporuka u najkraćem roku",
      "Licencu (ključ) šaljemo na email",
    ],
  },
  {
    title: "Windows 11 Professional Digitalna Licenca",
    shortTitle: "Windows 11 Pro",
    slug: "win-11-pro",
    image: "/images/products/win-11-pro.png",
    price: "45.00",
    infos: [
      "Izdavanje običnog i R1 računa",
      "Nova, nekorištena licenca - ključ",
      "Ključ aktivira jedno računalo doživotno",
      "Professional izdanje",
      "ESD (elektronička dostava putem emaila)",
      "Popust na količinu",
      "Uvijek na stanju, isporuka u najkraćem roku",
      "Licencu (ključ) šaljemo na email",
    ],
  },
  {
    title: "Windows 10 Home Digitalna Licenca",
    shortTitle: "Windows 11 Home",
    slug: "win-11-home",
    image: "/images/products/win-11-home.png",
    price: "43.00",
    infos: [
      "Izdavanje običnog i R1 računa",
      "Nova, nekorištena licenca - ključ",
      "Ključ aktivira jedno računalo doživotno",
      "Professional izdanje",
      "ESD (elektronička dostava putem emaila)",
      "Popust na količinu",
      "Uvijek na stanju, isporuka u najkraćem roku",
      "Licencu (ključ) šaljemo na email",
    ],
  },
  {
    title: "OFFICE 2021 Professional Plus doživotna licenca – ključ",
    shortTitle: "MSOffice 21 Pro",
    slug: "office-2021-professional-plus",
    image: "/images/products/office-2021-pro-pluss.png",
    price: "69.00",
    infos: [
      "Izdavanje običnog i R1 računa",
      "Nova, nekorištena licenca - ključ",
      "Ključ aktivira jedno računalo doživotno",
      "Professional izdanje",
      "ESD (elektronička dostava putem emaila)",
      "Popust na količinu",
      "Uvijek na stanju, isporuka u najkraćem roku",
      "Licencu (ključ) šaljemo na email",
      "Neprenosiva na druga računala",
      "Komaptibilna sa Windows 10 i 11",
      "Office paket uključuje: Word , Excel , PowerPoint , Outlook , Publisher , Access , Skype Bussines",
      "Za Mac računala na upit",
    ],
  },
  {
    title: "OFFICE 2019 Professional Plus doživotna licenca – ključ",
    shortTitle: "MSOffice 19 Pro",
    slug: "office-2019-professional-plus",
    image: "/images/products/office-2019-pro-plus.png",
    price: "49.00",
    infos: [
      "Izdavanje običnog i R1 računa",
      "Nova, nekorištena licenca - ključ",
      "Ključ aktivira jedno računalo doživotno",
      "Professional izdanje",
      "ESD (elektronička dostava putem emaila)",
      "Popust na količinu",
      "Uvijek na stanju, isporuka u najkraćem roku",
      "Licencu (ključ) šaljemo na email",
      "Neprenosiva na druga računala",
      "Komaptibilna sa Windows 10 i 11",
      "Office paket uključuje: Word , Excel , PowerPoint , Outlook , Publisher , Access , Skype Bussines",
      "Za Mac računala na upit",
    ],
  },
  {
    title: "MICROSOFT VISIO 2021 PROFESSIONAL",
    shortTitle: "Visio 21 Pro",
    slug: "vision-pro-2021",
    image: "/images/products/visio-pro-2021.png",
    price: "199.00",
    infos: [
      "Izdavanje običnog i R1 računa",
      "Najnovije Visio izdanje",
      "Nova, nekorištena licenca - ključ",
      "Ključ aktivira jedno računalo doživotno",
      "ESD (elektronička dostava putem emaila)",
      "Popust na količinu",
      "Uvijek na stanju, isporuka u najkraćem roku",
      "Licencu (ključ) šaljemo na email",
      "Neprenosiva na druga računala",
      "Komaptibilna sa Windows 10 i 11",
    ],
  },
  {
    title: "MICROSOFT PROJECT 2021 PROFESSIONAL",
    shortTitle: "Project 21 Pro",
    slug: "project-2021-professional",
    image: "/images/products/project-pro-2021.png",
    price: "269.00",
    infos: [
      "Izdavanje običnog i R1 računa",
      "Najnovije Visio izdanje",
      "Nova, nekorištena licenca - ključ",
      "Ključ aktivira jedno računalo doživotno",
      "ESD (elektronička dostava putem emaila)",
      "Popust na količinu",
      "Uvijek na stanju, isporuka u najkraćem roku",
      "Licencu (ključ) šaljemo na email",
      "Neprenosiva na druga računala",
      "Komaptibilna sa Windows 10 i 11",
    ],
  },
];
