name: Lint

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    environment: Build
    env:
      NODE_ENV: development
      MAILJET_APIKEY: ${{ secrets.MAILJET_APIKEY }}
      MAILJET_SECRET: ${{ secrets.MAILJET_SECRET }}
      MAILJET_FROM_EMAIL: ${{ secrets.MAILJET_FROM_EMAIL }}
      MAILJET_FROM_NAME: ${{ secrets.MAILJET_FROM_NAME }}
      MAILJET_TO_EMAIL: ${{ secrets.MAILJET_TO_EMAIL }}
      MAILJET_TO_NAME: ${{ secrets.MAILJET_TO_NAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: pnpm install
      - run: pnpm lint
